apiVersion: 2021-07-01 
location: eastus2 
name: acineu2pruebad01 
properties: 
  containers: 
  - name: helloworld 
    properties: 
      image: mcr.microsoft.com/azuredocs/aci-helloworld:latest 
      resources: 
        requests: 
          cpu: 1 
          memoryInGb: 1.5 
      ports: 
      - port: 80 
  osType: Linux 
  ipAddress: 
    type: Public 
    ports:  
    - protocol: tcp 
      port: 80 
type: Microsoft.ContainerInstance/containerGroups 